/*
 * Copyright 2024 git-crypt-revived contributors
 *
 * This file is part of git-crypt.
 *
 * git-crypt is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * git-crypt is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with git-crypt.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify the Program, or any covered work, by linking or
 * combining it with the OpenSSL project's OpenSSL library (or a
 * modified version of that library), containing parts covered by the
 * terms of the OpenSSL or SSLeay licenses, the licensors of the Program
 * grant you additional permission to convey the resulting work.
 * Corresponding Source for a non-source form of such a combination
 * shall include the source code for the parts of OpenSSL used as well
 * as that of the covered work.
 */

#include "sops.hpp"
#include "util.hpp"
#include "commands.hpp"
#include <sstream>
#include <fstream>
#include <cstdlib>

static std::string sops_get_executable ()
{
	std::string	sopsbin = "sops";
	try {
		sopsbin = get_git_config("sops.program");
	} catch (...) {
	}
	return sopsbin;
}

bool sops_is_available ()
{
	std::vector<std::string>	command;
	command.push_back(sops_get_executable());
	command.push_back("--version");
	std::stringstream		output;
	return successful_exit(exec_command(command, output));
}

std::string sops_get_version ()
{
	std::vector<std::string>	command;
	command.push_back(sops_get_executable());
	command.push_back("--version");
	std::stringstream		output;
	if (!successful_exit(exec_command(command, output))) {
		throw Sops_error("Failed to get SOPS version");
	}
	std::string	version = output.str();
	// Trim trailing whitespace/newlines
	while (!version.empty() && (version.back() == '\n' || version.back() == '\r' || version.back() == ' ')) {
		version.pop_back();
	}
	return version;
}

std::vector<std::string> sops_collect_age_recipients (const char* key_name)
{
	std::vector<std::string>	recipients;

	// Read age recipients from .git-crypt/keys/<name>/<version>/*.age files
	// The recipient is stored in the filename (hash) — we need the actual
	// recipient strings. For SOPS config, we look for a different source:
	// scan .gitattributes and git config for age recipients that have been added.

	// Primary approach: read from git config entries
	// git-crypt stores age recipients when add-age-recipient is called.
	// We also check the SOPS_AGE_RECIPIENTS environment variable.
	const char*	env_recipients = std::getenv("SOPS_AGE_RECIPIENTS");
	if (env_recipients && env_recipients[0]) {
		// Parse comma-separated recipients
		std::string	recip_str(env_recipients);
		size_t		pos = 0;
		while (pos < recip_str.size()) {
			size_t	next = recip_str.find(',', pos);
			if (next == std::string::npos) {
				next = recip_str.size();
			}
			std::string	r = recip_str.substr(pos, next - pos);
			// Trim whitespace
			while (!r.empty() && r.front() == ' ') r.erase(0, 1);
			while (!r.empty() && r.back() == ' ') r.pop_back();
			if (!r.empty()) {
				recipients.push_back(r);
			}
			pos = next + 1;
		}
	}

	// Also try git config
	try {
		std::string	config_recipients = get_git_config("git-crypt.sops-age-recipients");
		if (!config_recipients.empty()) {
			size_t		pos = 0;
			while (pos < config_recipients.size()) {
				size_t	next = config_recipients.find(',', pos);
				if (next == std::string::npos) {
					next = config_recipients.size();
				}
				std::string	r = config_recipients.substr(pos, next - pos);
				while (!r.empty() && r.front() == ' ') r.erase(0, 1);
				while (!r.empty() && r.back() == ' ') r.pop_back();
				if (!r.empty()) {
					recipients.push_back(r);
				}
				pos = next + 1;
			}
		}
	} catch (...) {
	}

	return recipients;
}

bool sops_generate_config (const std::string& output_path,
			   const std::vector<std::string>& age_recipients,
			   const std::vector<std::string>& file_patterns)
{
	std::ofstream	out(output_path);
	if (!out) {
		return false;
	}

	out << "# .sops.yaml — generated by git-crypt sops-config" << std::endl;
	out << "# This file configures SOPS to encrypt structured files (YAML/JSON/ENV)" << std::endl;
	out << "# using the same age recipients as git-crypt." << std::endl;
	out << "#" << std::endl;
	out << "# Files matching these patterns are encrypted by SOPS (partial encryption," << std::endl;
	out << "# keys visible, only values encrypted).  All other files matching" << std::endl;
	out << "# .gitattributes patterns are encrypted by git-crypt (full binary encryption)." << std::endl;
	out << std::endl;

	out << "creation_rules:" << std::endl;

	for (std::vector<std::string>::const_iterator pat(file_patterns.begin()); pat != file_patterns.end(); ++pat) {
		out << "  - path_regex: " << *pat << std::endl;

		if (!age_recipients.empty()) {
			out << "    age: ";
			for (size_t i = 0; i < age_recipients.size(); ++i) {
				if (i > 0) out << ",";
				out << age_recipients[i];
			}
			out << std::endl;
		}
	}

	out.close();
	return out.good();
}
